version: '2'
services:
  DailyCheckout:
     image: 10.0.0.96:5000/my_os/node:v1.1
     hostname: DailyCheckout
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=104
     networks: 
       - docker_gwbridge
     ports:
       - ${port_DailyCheckout}:${port_DailyCheckout}
     volumes:
       - /demo/node/DailyCheckout:/data
     privileged: true
     tty: true
  DevFileServer:
     image: 10.0.0.96:5000/my_os/node:v1.1
     hostname: DevFileServer
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=104
     networks: 
       - docker_gwbridge
     ports:
       - ${port_DevFileServer}:${port_DevFileServer}
     volumes:
       - /demo/node/devfile-jtran:/data
     privileged: true
     tty: true
  FrontendServer:
     image: 10.0.0.96:5000/my_os/node:v1.1
     hostname: FrontendServer
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=104
     networks: 
       - docker_gwbridge
     ports:
       - ${port_FrontendServer}:${port_FrontendServer}
     volumes:
       - /demo/node/FrontendServer:/data
     privileged: true
     tty: true
  jtran-service:
     image: 10.0.0.96:5000/my_os/node:v1.1
     hostname: jtran_service
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=104
     networks: 
       - docker_gwbridge
     ports:
       - ${port_jtran_service}:${port_jtran_service}
     volumes:
       - /demo/node/devfile-jtran:/data
     privileged: true
     tty: true
  TradServer:
     image: 10.0.0.96:5000/my_os/node:v1.1
     hostname: TradServer
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=104
     networks: 
       - docker_gwbridge
     ports:
       - ${port_TradServer}:${port_TradServer}
     volumes:
       - /demo/node/TradServer:/data
     privileged: true
     tty: true
  FlatCard:
     image: 10.0.0.96:5000/my_os/node:v1.1
     hostname: FlatCard
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=104
     networks: 
       - docker_gwbridge
     ports:
       - ${port_FlatCard}:${port_FlatCard}
     volumes:
       - /demo/node/FlatCard:/data
     privileged: true
     tty: true
  Online-xf:
     image: 10.0.0.96:5000/my_os/node:v1.1
     hostname: Online-xf
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=104
     networks: 
       - docker_gwbridge
     ports:
       - ${port_Online_xf}:${port_Online_xf}
     volumes:
       - /demo/node/Online-xf:/data
     privileged: true
     tty: true
  jmsg-service:
     image: 10.0.0.96:5000/my_os/node:v1.1
     hostname: jmsg-service
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=104
     networks: 
       - docker_gwbridge
     ports:
       - ${port_jmsg_service}:${port_jmsg_service}
     volumes:
       - /demo/node/jmsg-service:/data
     privileged: true
     tty: true
  dev-tran-service:
     image: 10.0.0.96:5000/my_os/node:v1.1
     hostname: dev-tran-service
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=104
     networks: 
       - docker_gwbridge
     ports:
       - ${port_dev_tran_service}:${port_dev_tran_service}
     volumes:
       - /demo/node/dev-tran-service:/data
     privileged: true
     tty: true
